name: CI/CD for Razor Pages App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore dependencies
        run: dotnet restore ./TASK_4/TASK_4.sln 
      
      - name: Build
        run: dotnet build ./TASK_4/TASK_4.sln --no-restore
      
      - name: Run tests
        run: dotnet test ./TASK_4/TASK_4.sln --no-build --verbosity normal
      
      - name: Publish
        run: dotnet publish ./TASK_4/TASK_4/TASK_4.csproj -c Release -o ./publish-output
